### ISSUE TITLE
The One Probe / Hwyla compat?

### ISSUE THREAD

**Issue by BrisingrAerowing** [tiffanyjager/horse-colors#2]
Would it be possible to add The One Probe / Hwyla compat for horse stats? I personally use TOP, as I find it works better.

**Comment by Archests** [comment]
^ This please

**Comment by datadelft** [comment]
how can we see the stats at the moment? it isn't displayed in hwyla or when mounting the horse

**Comment by BrisingrAerowing** [comment]
There's a config option called horseDebug, which puts horse info on the F3 screen if you are holding a stick (as long as the option is enabled, which it isn't by default).

**Comment by tiffanyjager** [comment]
This is not a compatibility issue. Hwyla and The One Probe do not show horse stats.

**Comment by BrisingrAerowing** [comment]
TOP does when you use a probe. It's a config option. IIRC it's on by default.

**Comment by tiffanyjager** [comment]
Oh, I see. Their code specifically checks if the entity is an instance of EntityHorse. I think it will be possible, but I probably won't get around to it for a while.

**Comment by tiffanyjager** [comment]
The One Probe can fix this for modded horses in general just by replacing EntityHorse with AbstractHorseEntity as Wawla does. This is their problem, not mine.

Hwyla and wawla already work exactly the same as with vanilla horses and have no compatibility issues.
