### ISSUE TITLE
On 1.12, horses lack localizations

### ISSUE THREAD

**Issue by Sunconure11** [tiffanyjager/horse-colors#5]
![Screenshot 2020-03-22 12 35 52](https://user-images.githubusercontent.com/5614902/77254816-c4dd6200-6c39-11ea-8698-885f646164e4.png)

**Comment by tiffanyjager** [comment]
The lang file was named wrong, apparently. It should be fixed whenever Curseforge decides to approve the new file. By the way, how are you getting all that info? Hwyla only shows me the name, health, and mod.

**Comment by Sunconure11** [comment]
I'm also using WAWLA

**Comment by tiffanyjager** [comment]
Ok, thanks. Closing as it should be fixed now.

**Comment by Sunconure11** [comment]
Side note, are there plans to bring any of the color changes from donkeys/mules as well as any other color patterns from newer versions of MC to 1.12.2? Yes, I'm working on a 1.15 pack, but I'm just curious.

**Comment by tiffanyjager** [comment]
Right now I'm thinking that once horses, donkeys, and mules are fully done, I'll backport everything to 1.14 and 1.12 before moving on to the next project. But that probably won't be for a while, and when it does come time I might not feel like banging my head against compile errors enough to actually do it.
